seed: 20220609
proj_dir: "/home/shinhan/projects/plant_sci_hist"
work_dir: "_converted"

aux_data:
  aux_dir: "data"
  usda_plant_db: "USDA_Plants_Database.txt"
  names_dmp_path: "names.dmp"
  nodes_dmp_path: "nodes.dmp"
  # Should have "Date", "txt" columns
  corpus_file: "corpus_plant_10000_test.csv.gz"
  ts_for_bins_file: "table4_4_bin_timestamp_date.tsv"

set_taxa:
  base_taxa: "Viridiplantae"
  target_level: "genus"
  drop: ['Matthiola', 'California', 'Dichrostachys']
  topX: 100

# Send a subset docs at a time so no memory issues when getting matches
n_subset: 5000

time_bin:
  num_bins: 50
